/* Generated by ./script/iconify.js */
/* eslint-disable */
import IconBase from './IconBase'

const IconChevron = ({  ...rest }) => {
  const classes = ['icon',
    'icon--chevron']

  return (
    <IconBase className={classes.toString()} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 8"{...rest}><path className="path1" fill="none" fillRule="evenodd" stroke="#888" d="M1 0l4 4-4 4"/></IconBase>
  )
}

export default IconChevron
/* eslint-enable */
